name: cobgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=12.1
  - plyfile
  - python=3.10
  - pip=22.3.1
  - pytorch=2.3.1
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
